### ISSUE TITLE
Improve grid printout

### ISSUE THREAD

**Issue by ertyertyerty** [scottwedge/sudoku#2]
Might I suggest that the 0th, 3rd, 6th and 9th lines of the grid be "doubled"?
So for the horizontal lines those would use '=' instead of '-'.
For the vertical lines I suppose you can only use '||' instead of '|'.
Which means you'll also have to add extra '+' on the doubled vertical lines.
Sample:
++=====+=====+=====++=====+=====+=====++=====+=====+=====++
|| [6] | [8] | [4] || [2] | [7] | [1] || [5] | [9] | [3] ||
++-----+-----+-----++-----+-----+-----++-----+-----+-----++
|| [2] | [3] | [5] || [9] | [4] | [6] || [8] | [7] | [1] ||
++-----+-----+-----++-----+-----+-----++-----+-----+-----++
|| [1] | [7] | [9] || [5] | [3] | [8] || [2] | [6] | [4] ||
++=====+=====+=====++=====+=====+=====++=====+=====+=====++
|| [9] | [4] | [3] || [6] | [8] | [5] || [7] | [1] | [2] ||
...

**Comment by scottwedge** [comment]
Fixed by commit [ed16826]
